#13 updated dependencies
exasol/java-util-logging-testing pull request #14
Opened 2022-08-29 15:40 UTC by ckunki

fixes #13

2022-08-29 17:13 UTC, tomuben commented on doc/changes/changes_2.0.2.md
> +Updated dependencies especially project-keeper maven plugin and by that fixed report for broken links to opensource.org.
```suggestion
Updated dependencies, especially project-keeper maven plugin and by that fixed check for broken links to opensource.org.
```

2022-08-29 17:14 UTC, tomuben reviewed
Check my comments

2022-08-30 07:17 UTC, kaklakariada requested changes

2022-08-30 07:17 UTC, kaklakariada commented on .classpath
>  	</classpathentry>
Remove .classpath and .project and add it to .gitignore.

2022-08-30 07:17 UTC, kaklakariada commented on .settings/org.eclipse.core.resources.prefs
> +eclipse.preferences.version=1
Delete & ignore this file

2022-08-30 07:17 UTC, kaklakariada commented on pom.xml
>                          <goals>
Remove `<configuration>` (moved to .project-keeper.yml)

2022-08-30 07:17 UTC, kaklakariada commented on .project-keeper.yml
> +      - jar_artifact
```suggestion
```
No need to upload artifact to github release. We deploy to maven central only.

This means you can delete the release_droid_upload_github_release_assets.yml workflow.

2022-08-30 07:17 UTC, kaklakariada commented on pom.xml
>          <junit.version>5.8.1</junit.version>
```suggestion
        <junit.version>5.9.0</junit.version>
```

2022-08-30 10:01 UTC, kaklakariada approved these changes

2022-08-30 10:01 UTC, merged